version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: /bin/sh /usr/src/app/scripts/docker/start-django.sh
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        container_name: db
        env_file:
            - .env
