# Generated by Django 4.1.1 on 2022-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="money",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
