# Generated by Django 4.1.1 on 2022-10-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="list",
        ),
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.category",
            ),
            preserve_default=False,
        ),
    ]
