# Generated by Django 4.1.1 on 2022-10-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_alter_list_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sport", "Sport"),
                    ("Health", "Health"),
                    ("Insurance", "Insurance"),
                    ("Food", "Food"),
                    ("Travel", "Travel"),
                ],
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
