# Generated by Django 4.1.1 on 2022-10-02 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0008_transaction_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="List",
            new_name="BudgetList",
        ),
    ]
